import sys
sys.path.insert(0, r"C:\Users\cpell\OneDrive - PeakMade Real Estate\VS_Code_Files\Help Ticket Triage\bi-triage-agent\scripts")
from helpers import load_env, SafeConnection

env = load_env()
conn = SafeConnection(env, "DB_APP_SUPPORT", None, direct=True)
cur = conn.execute("""
    SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='PROPERTY_0'
    ORDER BY ORDINAL_POSITION
""")
all_cols = [r[0] for r in cur.fetchall()]

# Replicate the JS known sets
detail_sections = {
    'Identity': ['PROPERTY_KEY','PROPERTY_NAME','ADDRESS_1','ADDRESS_2','ADDRESS_CITY','ADDRESS_STATE','ADDRESS_ZIP','ADDRESS_COUNTY','ADDRESS_COUNTRY','PHONE_1','PHONE_2','PHONE_FAX','EMAIL','LATITUDE','LONGITUDE','TIME_ZONE'],
    'Classification': ['PROPERTY_TYPE','PROPERTY_GROUP','MARKET_CITY_STATE','OWNER','OWNER_GROUP','COMPANY','MANAGEMENT_TYPE','SCHOOL_NAME','SCHOOL_ACRONYM','SCHOOL_INITIALS','SCHOOL_MASCOT','LIST_MANAGED','LIST_STATUS','LIST_TRANSITIONTYPE','LIST_TYPE','STATUS','LIFECYCLE_STATUS','TRANSITION_TYPE','SOURCE_SYSTEM','CURRENT_PHASE'],
    'Financials': ['APARTMENT_COUNT','APARTMENT_COUNT_BILLING','BED_COUNT_CUSTOM','BED_COUNT_BILLING','BED_COUNT_COMPILED','BED_COUNT_STATIC','BUILDING_COUNT','GROSS_SQFT','RENTABLE_SQFT','BUILD_YEAR','SAME_STORE_YEAR','PAYROLL_ENTITY','ENTITY_NAME','ENTITY_NUMBER','LEGAL_ENTITY','TAX_ID','BILLING_ALLOCATION_PARTNERS','BILLING_ALLOCATION_PCT'],
    'Dates': ['DATE_CREATED','DATE_LAST_UPDATED','DATE_MGMT_TAKEOVER','DATE_STABILIZED','DATE_DISPOSITIONED','DATE_LIFECYCLE','DATE_MIGRATED','DATE_ANTICIPATED_TAKEOVER','DATE_DATA_FREEZE','DATE_ADDED_TO_DW','DATE_STATUS'],
    'URLs': ['URL_WEBSITE','URL_FACEBOOK','URL_INSTAGRAM','URL_TWITTER','URL_SHARED_FOLDER','GOOGLE_PROPERTY_LINK','GOOGLE_PROPERTY_TYPE'],
    'Notes': ['NOTES','OFFICE_HOURS_1','OFFICE_HOURS_2','OFFICE_HOURS_3','OFFICE_HOURS_4','OFFICE_HOURS_5'],
}

staff_fields = []
staff_roles = {
    'PM': ['PM_NAME','PM_EMAIL','PM_EMP_CODE'],
    'RM': ['RM_NAME','RM_EMAIL','RM_EMP_CODE'],
    'RVP': ['RVP_NAME','RVP_EMAIL','RVP_EMP_CODE'],
    'AM': ['AM_NAME','AM_EMAIL','AM_EMP_CODE'],
    'LM': ['LM_NAME','LM_EMAIL','LM_EMP_CODE'],
    'EXEC_DIR': ['EXEC_DIR_NAME','EXEC_DIR_EMAIL','EXEC_DIR_EMP_CODE'],
    'MAINT_SUPV': ['MAINT_SUPV_NAME','MAINT_SUPV_EMAIL','MAINT_SUPV_EMP_CODE'],
    'ACCOUNTANT': ['ACCOUNTANT','ACCOUNTANT_EMP_CODE'],
    'CONTROLLER': ['CONTROLLER','CONTROLLER_EMP_CODE'],
    'ACCOUNTING_MGR': ['ACCOUNTING_MGR','ACCOUNTING_MGR_EMP_CODE'],
    'ASSISTANT_CONTROLLER': ['ASSISTANT_CONTROLLER','ASSISTANT_CONTROLLER_EMP_CODE'],
    'RESIDENT_DIR': ['RESIDENT_DIR_NAME','RESIDENT_DIR_EMAIL','RESIDENT_DIR_EMP_CODE'],
    'RAM': ['RAM_NAME','RAM_EMP_CODE'],
    'RMLS': ['RMLS_NAME','RMLS_EMAIL','RMLS_EMP_CODE'],
    'ASSET_MGR': ['ASSET_MGR_NAME','ASSET_MGR_EMAIL'],
}
for fields in staff_roles.values():
    staff_fields.extend(fields)

flags = ['FLAG_REPORTABLE','FLAG_MANAGED','FLAG_DISPOSITIONED','FLAG_LEASEUP','FLAG_STABILIZED',
    'FLAG_PENDING','FLAG_TENTATIVE','FLAG_CORPORATE_LOCATION','FLAG_NON_PROPERTY','FLAG_SUBPROPERTY',
    'FLAG_CONVENTIONAL_ONLY','FLAG_DATA_FREEZE','FLAG_FANNIE_FREDDIE_MORTGAGE','FLAG_MIXED_USE',
    'FLAG_RETAIL','FLAG_STUDENT_ONLY','FLAG_USE_TEMP_ADDRESS','FLAG_MIGRATED','FLAG_PHASE_0',
    'FLAG_PHASE_1','FLAG_PHASE_2','FLAG_PHASE_3','FLAG_PHASE_4','FLAG_PHASE_5','FLAG_PHASE_6',
    'FLAG_PHASE_7','FLAG_PHASE_8','FLAG_PHASE_9','FLAG_PHASE_10']

hidden = {'AutoIDField', 'RowVer'}

all_known = set()
for fields in detail_sections.values():
    all_known.update(fields)
all_known.update(staff_fields)
all_known.update(flags)
all_known.update(hidden)

missing = [c for c in all_cols if c not in all_known]
print(f"Total columns: {len(all_cols)}")
print(f"Known columns: {len(all_known)}")
print(f"\nColumns NOT explicitly listed ({len(missing)}):")
for c in missing:
    print(f"  {c}")
