import sys
sys.path.insert(0, r"C:\Users\cpell\OneDrive - PeakMade Real Estate\VS_Code_Files\Help Ticket Triage\bi-triage-agent\scripts")
from helpers import load_env, SafeConnection

env = load_env()
conn = SafeConnection(env, "DB_APP_SUPPORT", None, direct=True)
cur = conn.execute("""
    SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA='dbo' AND TABLE_NAME='PROPERTY_0'
    ORDER BY ORDINAL_POSITION
""")
all_cols = [r[0] for r in cur.fetchall()]

# Updated known sets
detail_sections_fields = [
    'PROPERTY_KEY','PROPERTY_NAME','ADDRESS_1','ADDRESS_2','ADDRESS_CITY','ADDRESS_STATE','ADDRESS_ZIP','ADDRESS_COUNTY','ADDRESS_COUNTRY','PHONE_1','PHONE_2','PHONE_FAX','EMAIL','LATITUDE','LONGITUDE','TIME_ZONE','ALTERNATE_ID_1','ALTERNATE_ID_2','ALTERNATE_ID_3','SUBPROPERTY_NAME','IMAGE_KEY_FLAG','IMAGE_KEY_PROPERTY',
    'TEMP_STREET','TEMP_CITY','TEMP_STATE','TEMP_ZIP',
    'PROPERTY_TYPE','PROPERTY_TYPE_KEY','PROPERTY_GROUP','PROPERTY_GROUP_KEY','MARKET_CITY_STATE','MARKET_CITY','MARKET_STATE','MARKET_KEY','OWNER','OWNER_GROUP','OWNER_SHORT','OWNER_GROUP_SHORT','COMPANY','MANAGEMENT_TYPE','MANAGEMENT_TYPE_KEY','SCHOOL_NAME','SCHOOL_ACRONYM','SCHOOL_INITIALS','SCHOOL_MASCOT','LIST_MANAGED','LIST_STATUS','LIST_TRANSITIONTYPE','LIST_TYPE','STATUS','LIFECYCLE_STATUS','LIFECYCLE_KEY','LIFECYCLE_STEP','TRANSITION_TYPE','TRANSITION_TYPE_KEY','SOURCE_SYSTEM','SOURCE_SYSTEM_ID','SOURCE_SYSTEM_SUB_ID','CURRENT_PHASE','MSA','PROPERTY_LIST_CODE','PROPERTY_AR_CODE',
    'APARTMENT_COUNT','APARTMENT_COUNT_BILLING','BED_COUNT_CUSTOM','BED_COUNT_BILLING','BED_COUNT_COMPILED','BED_COUNT_STATIC','BED_COUNT_STATIC_PY','BUILDING_COUNT','GROSS_SQFT','RENTABLE_SQFT','BUILD_YEAR','SAME_STORE_YEAR','SAME_STORE_YEAR_REVERSE_ID','STABILIZED_YEAR','PAYROLL_ENTITY','ENTITY_NAME','ENTITY_NUMBER','LEGAL_ENTITY','TAX_ID','BILLING_ALLOCATION_PARTNERS','BILLING_ALLOCATION_PCT','HEADCOUNT','COUNT','FINANCIAL_PUBLICATION_DAY','LENDER_NAME','MGMT_ENTITY',
    'GOAL_GOOGLE_RATING','GOAL_ORA','GOAL_REPUTATION',
    'DATE_CREATED','DATE_LAST_UPDATED','DATE_MGMT_TAKEOVER','DATE_STABILIZED','DATE_DISPOSITIONED','DATE_LIFECYCLE','DATE_MIGRATED','DATE_ANTICIPATED_TAKEOVER','DATE_DATA_FREEZE','DATE_ADDED_TO_DW','DATE_STATUS',
    'LEGACY_ENTRATA_ID','LEGACY_ONESITE_ID','LEGACY_SUBPROPERTY_ID_ENTRATA','LEGACY_SUBPROPERTY_ID_ONESITE','LEGACY_SUBPROPERTY_NAME_1','LEGACY_SUBPROPERTY_NAME_2','LEGACY_SUBPROPERTY_NUMBER','LEGACY_NAME_1','LEGACY_NAME_2','LEGACY_NAME_3','LEGACY_NAME_4','LEGACY_NAME_5','LEGACY_NAME_6',
    'PREVIOUS_MGMT_COMPANY','PREVIOUS_MGMT_CONTACT','PREVIOUS_PMS','PREVIOUS_NAA',
    'URL_WEBSITE','URL_FACEBOOK','URL_INSTAGRAM','URL_TWITTER','URL_SHARED_FOLDER','GOOGLE_PROPERTY_LINK','GOOGLE_PROPERTY_TYPE','URL_TRANSITION_CHECKLIST',
    'VENDOR_01','VENDOR_02','VENDOR_03','VENDOR_04','VENDOR_05','VENDOR_06','VENDOR_07','VENDOR_08','VENDOR_09','VENDOR_10','VENDOR_11','VENDOR_12','VENDOR_13','VENDOR_14','VENDOR_15','VENDOR_COMMENTS_01','VENDOR_COMMENTS_02',
    'NOTES','OFFICE_HOURS_1','OFFICE_HOURS_2','OFFICE_HOURS_3','OFFICE_HOURS_4','OFFICE_HOURS_5',
]

staff_fields = [
    'PM_NAME','PM_EMAIL','PM_EMP_CODE','RM_NAME','RM_EMAIL','RM_EMP_CODE','RVP_NAME','RVP_EMAIL','RVP_EMP_CODE',
    'AM_NAME','AM_EMAIL','AM_EMP_CODE','LM_NAME','LM_EMAIL','LM_EMP_CODE',
    'EXEC_DIR_NAME','EXEC_DIR_EMAIL','EXEC_DIR_EMP_CODE','MAINT_SUPV_NAME','MAINT_SUPV_EMAIL','MAINT_SUPV_EMP_CODE',
    'ACCOUNTANT','ACCOUNTANT_EMP_CODE','CONTROLLER','CONTROLLER_EMP_CODE',
    'ACCOUNTING_MGR','ACCOUNTING_MGR_EMP_CODE','ASSISTANT_CONTROLLER','ASSISTANT_CONTROLLER_EMP_CODE',
    'RESIDENT_DIR_NAME','RESIDENT_DIR_EMAIL','RESIDENT_DIR_EMP_CODE',
    'RAM_NAME','RAM_EMP_CODE','RMLS_NAME','RMLS_EMAIL','RMLS_EMP_CODE',
    'ASSET_MGR_NAME','ASSET_MGR_EMAIL',
]

flags = ['FLAG_ACTIVE','FLAG_REPORTABLE','FLAG_MANAGED','FLAG_DISPOSITIONED','FLAG_LEASEUP','FLAG_STABILIZED',
    'FLAG_PENDING','FLAG_TENTATIVE','FLAG_CORPORATE_LOCATION','FLAG_NON_PROPERTY','FLAG_SUBPROPERTY',
    'FLAG_CONVENTIONAL_ONLY','FLAG_DATA_FREEZE','FLAG_FANNIE_FREDDIE_MORTGAGE','FLAG_MIXED_USE',
    'FLAG_RETAIL','FLAG_STUDENT_ONLY','FLAG_USE_TEMP_ADDRESS','FLAG_MIGRATED','FLAG_PHASE_0',
    'FLAG_PHASE_1','FLAG_PHASE_2','FLAG_PHASE_3','FLAG_PHASE_4','FLAG_PHASE_5','FLAG_PHASE_6',
    'FLAG_PHASE_7','FLAG_PHASE_8','FLAG_PHASE_9','FLAG_PHASE_10']

hidden = {'AutoIDField', 'RowVer'}

all_known = set(detail_sections_fields) | set(staff_fields) | set(flags) | hidden
missing = [c for c in all_cols if c not in all_known]
print(f"Total columns: {len(all_cols)}")
print(f"Known columns: {len(all_known)}")
print(f"Still missing: {len(missing)}")
for c in missing:
    print(f"  {c}")
