"""Module registry - all AppHub modules defined here."""

# Mapping from APP_LIST.App_ID (int) to internal string ID
APP_ID_MAP = {
    14: "apphub_maintenance",
    6: "canada_market_survey",
    22: "cultivate_nomination",
    9: "employee_data_manager",
    20: "fasttrack_recommendation",
    15: "market_benchmark",
    21: "mentor_certification",
    1: "milestones",
    24: "mindset_award_nomination",
    16: "new_hire_alert",
    25: "peak_link_idea",
    27: "promotion_transfer_alert",
    8: "property_data_manager",
    7: "rent_forecasting_system",
    35: "rent_forecasting_2",
    19: "rush_check_request",
    10: "sam_ad_spend_planning",
    11: "sam_contract_manager",
    18: "special_handling_form",
    12: "support_data_manager",
    26: "the_pitch_workflow",
    17: "vendor_setup_form",
    4: "ach_request",
    3: "prepaid_visa_compliance",
    5: "property_data_manager_pdm",
    2: "rm_inspections",
}

# Reverse: string ID → App_ID
STRING_ID_TO_APP_ID = {v: k for k, v in APP_ID_MAP.items()}

MODULES = [
    {
        "id": "apphub_maintenance",
        "name": "AppHub Maintenance",
        "icon": "fa-solid fa-gears",
        "color": "#64748b",
        "description": "Manage module registry, audiences, and user access for the AppHub platform.",
        "type": "flask",
        "route": "/maintenance/",
        "admin_only": True,
    },
    {
        "id": "canada_market_survey",
        "name": "Canada Market Survey",
        "icon": "fa-solid fa-mountain-city",
        "color": "#14b8a6",
        "description": "Market survey tools for Canadian property markets.",
        "type": "powerapps",
        "route": None,
        "admin_only": False,
    },
    {
        "id": "cultivate_nomination",
        "name": "Cultivate Nomination",
        "icon": "fa-solid fa-wand-magic-sparkles",
        "color": "#a855f7",
        "description": "Nominate team members for the Cultivate recognition program.",
        "type": "flask",
        "route": "/cultivate/",
        "admin_only": False,
    },
    {
        "id": "employee_data_manager",
        "name": "Employee Data Manager",
        "icon": "fa-solid fa-users-gear",
        "color": "#3b82f6",
        "description": "Manage employee title groups, Entrata mappings, and soft termination overrides.",
        "type": "flask",
        "route": "/edm/",
        "admin_only": False,
    },
    {
        "id": "fasttrack_recommendation",
        "name": "FastTrack Recommendation",
        "icon": "fa-solid fa-forward-fast",
        "color": "#f59e0b",
        "description": "Submit and track FastTrack promotion recommendations.",
        "type": "flask",
        "route": "/fasttrack/",
        "admin_only": False,
    },
    {
        "id": "market_benchmark",
        "name": "Market Benchmark",
        "icon": "fa-solid fa-house",
        "color": "#22c55e",
        "description": "Benchmark property performance against market comparables.",
        "type": "flask",
        "route": "/mrb/",
        "admin_only": False,
    },
    {
        "id": "mentor_certification",
        "name": "Mentor Certification",
        "icon": "fa-solid fa-location-dot",
        "color": "#06b6d4",
        "description": "Track and manage mentor certification progress.",
        "type": "flask",
        "route": "/mentor-cert/",
        "admin_only": False,
    },
    {
        "id": "milestones",
        "name": "Milestones",
        "icon": "fa-solid fa-calendar-check",
        "color": "#8b5cf6",
        "description": "Track employee milestones and anniversaries.",
        "type": "flask",
        "route": "/milestones/",
        "admin_only": False,
    },
    {
        "id": "mindset_award_nomination",
        "name": "Mindset Award Nomination",
        "icon": "fa-solid fa-globe",
        "color": "#10b981",
        "description": "Nominate team members for Mindset Awards.",
        "type": "flask",
        "route": "/mindset/",
        "admin_only": False,
    },
    {
        "id": "new_hire_alert",
        "name": "New Hire Alert",
        "icon": "fa-solid fa-user-plus",
        "color": "#ef4444",
        "description": "Alert notifications for new employee hires.",
        "type": "flask",
        "route": "/new-hire/",
        "admin_only": False,
    },
    {
        "id": "peak_link_idea",
        "name": "Peak Link",
        "icon": "fa-solid fa-lightbulb",
        "color": "#10b981",
        "description": "Submit and track ideas through the Peak Link program.",
        "type": "flask",
        "route": "/peak-link/",
        "admin_only": False,
    },
    {
        "id": "promotion_transfer_alert",
        "name": "Promotion/Transfer Alert",
        "icon": "fa-solid fa-people-arrows",
        "color": "#f97316",
        "description": "Submit Promotion/Transfer Alert (PAF) forms for associate role changes.",
        "type": "flask",
        "route": "/paf/",
        "admin_only": False,
    },
    {
        "id": "property_data_manager",
        "name": "Property Data Manager",
        "icon": "fa-solid fa-house",
        "color": "#0ea5e9",
        "description": "Manage property data, groups, markets, and field overrides.",
        "type": "flask",
        "route": "/pdm/",
        "admin_only": False,
    },
    {
        "id": "rent_forecasting_2",
        "name": "Rent Forecasting 2.0",
        "icon": "fa-solid fa-chart-line",
        "color": "#67e8e0",
        "description": "Next-generation rent forecasting with tier editing, market comps, and stakeholder charts.",
        "type": "flask",
        "route": "/rfs2/",
        "admin_only": False,
    },
    {
        "id": "rent_forecasting_system",
        "name": "Rent Forecasting System",
        "icon": "fa-solid fa-chart-line",
        "color": "#6366f1",
        "description": "Forecast rent trends and pricing analytics.",
        "type": "flask",
        "route": "/rfs/",
        "admin_only": False,
    },
    {
        "id": "rush_check_request",
        "name": "Rush Check Request",
        "icon": "fa-solid fa-money-check-dollar",
        "color": "#f59e0b",
        "description": "Submit and track rush check requests.",
        "type": "flask",
        "route": "/rush-check/",
        "admin_only": False,
    },
    {
        "id": "sam_ad_spend_planning",
        "name": "SAM Ad Spend Planning",
        "icon": "fa-solid fa-rectangle-ad",
        "color": "#ec4899",
        "description": "Plan and track SAM advertising spend by property and GL code.",
        "type": "flask",
        "route": "/sam-ad-spend/",
        "admin_only": False,
    },
    {
        "id": "sam_contract_manager",
        "name": "SAM Contract Manager",
        "icon": "fa-solid fa-file-contract",
        "color": "#84cc16",
        "description": "Manage SAM vendor contracts and agreements.",
        "type": "flask",
        "route": "/sam-contracts/",
        "admin_only": False,
    },
    {
        "id": "special_handling_form",
        "name": "Special Handling Form",
        "icon": "fa-solid fa-house",
        "color": "#f43f5e",
        "description": "Submit special handling payment requests for vendor invoices.",
        "type": "flask",
        "route": "/special-handling/",
        "admin_only": False,
    },
    {
        "id": "support_data_manager",
        "name": "Support Data Manager",
        "icon": "fa-solid fa-database",
        "color": "#0891b2",
        "description": "Manage support data tables and configurations.",
        "type": "powerapps",
        "route": None,
        "admin_only": False,
    },
    {
        "id": "the_pitch_workflow",
        "name": "The Pitch Workflow",
        "icon": "fa-solid fa-lightbulb",
        "color": "#f59e0b",
        "description": "The Pitch idea submission and approval workflow.",
        "type": "flask",
        "route": "/pitch/",
        "admin_only": False,
    },
    {
        "id": "vendor_setup_form",
        "name": "Vendor Setup Form",
        "icon": "fa-solid fa-handshake",
        "color": "#059669",
        "description": "Vendor onboarding and setup form management.",
        "type": "flask",
        "route": "/vendor-setup/",
        "admin_only": False,
    },
    {
        "id": "ach_request",
        "name": "ACH Request",
        "icon": "fa-solid fa-building-columns",
        "color": "#0d9488",
        "description": "Submit ACH bank transfer requests.",
        "type": "powerapps",
        "route": None,
        "admin_only": False,
    },
    {
        "id": "prepaid_visa_compliance",
        "name": "Prepaid Visa Compliance",
        "icon": "fa-solid fa-credit-card",
        "color": "#dc2626",
        "description": "Prepaid Visa card compliance tracking.",
        "type": "powerapps",
        "route": None,
        "admin_only": False,
    },
    {
        "id": "property_data_manager_pdm",
        "name": "Property Data Manager (PDM)",
        "icon": "fa-solid fa-house-circle-check",
        "color": "#7c3aed",
        "description": "Legacy property data manager.",
        "type": "powerapps",
        "route": None,
        "admin_only": False,
    },
    {
        "id": "rm_inspections",
        "name": "RM Inspections",
        "icon": "fa-solid fa-clipboard-check",
        "color": "#b45309",
        "description": "Regional manager property inspection tracking.",
        "type": "powerapps",
        "route": None,
        "admin_only": False,
    },
]

# Inject integer App_ID into each module for DB/favorites lookups
for _m in MODULES:
    _m["app_id"] = STRING_ID_TO_APP_ID.get(_m["id"])


def get_module(module_id):
    """Get a module by its ID."""
    return next((m for m in MODULES if m["id"] == module_id), None)


def get_visible_modules(is_admin=False):
    """Get modules visible to the current user."""
    if is_admin:
        return MODULES
    return [m for m in MODULES if not m["admin_only"]]
